### ISSUE TITLE
05.09.화 - 안드로이드 최적화

### ISSUE THREAD

**Issue by chaejunlee** [Beamworks-Inc/ChatAI-KIMES#7]
## 확인되는 사항들

- 안드로이드는 키보드가 나타났을 때 자동으로 키보드 높이 만큼의 패딩이 bottom에 주어지는 것으로 확인
  - 사용하는 기기 종류를 알아야 함
- 보여지는 viewport 너머 위아래로 스크롤을 막기 위해 스크롤 할 때 마다 원점으로 화면을 돌리고 있음
  - 되게 불안정해 보이고 stutter하는 것 같이 보임
  - 조금 더 부드러운 스크롤 모션을 넣거나 아예 스크롤이 안 되게 막아야 할 듯
- 상황에 따라서 보여지는 채팅 섹션이 너무 작음
  - 어떻게 해야할지 디자인/기획과 의견 나눠서 다시 확인할 필요가 있어보임
<img width="762" alt="Screenshot 2023-05-09 at 9 24 30" src="https://user-images.githubusercontent.com/48273875/236964116-115ac25c-75ef-4557-b1da-1adc68a0f9e6.png">

## TASK

- [x] 사용하는 기기 종류 알아내기
- [ ] 스크롤 안 되게 하는 방법 알아내기
- [x] 부드럽게 스크롤 되는 방안도 생각해보기
- [x] 디자인/기획 쪽하고 이슈 공유하기
